pub struct Substitution {
    pub name: &'static str,
    pub text: &'static str,
}

pub const SUBSTITUTIONS: &[Substitution] = &[
    // Custom ASCII Art and Text Emotes
    Substitution { name: "disapproval", text: "(ಠ_ಠ)" },
    Substitution { name: "bugeyes", text: "(⊙_◎)" },
    Substitution { name: "dogshrug", text: "¯\\_🐶_/¯" },
    Substitution { name: "facepalm", text: "(－‸ლ)" },
    Substitution { name: "flip", text: "(╯°□°)╯︵ ┻━┻" },
    Substitution { name: "fu", text: "t(-__-t)" },
    Substitution { name: "heresatable", text: "┬─┬ ノ( ゜-゜ノ)" },
    Substitution { name: "javaflip", text: "(╯°□°)╯︵ ┻ɐʌɐɾ┻" },
    Substitution { name: "kungfuhamster", text: "    ()__()\n    / o o\\   ;\n   |'=Y=';-/\n   { \\  / }\n    mmm mmm   " },
    Substitution { name: "omw", text: "On my way!" },
    Substitution { name: "rage", text: "ಠ益ಠ" },
    Substitution { name: "rageflip", text: "(ノಠ益ಠ)ノ彡┻━┻" },
    Substitution { name: "rockhand", text: "\\m/ (>_<) \\m/" },
    Substitution { name: "shrug", text: "¯\\_(ツ)_/¯" },
    Substitution { name: "shrugtable", text: "┻━┻ ︵ ¯\\(ツ)/¯ ︵ ┻━┻" },
    Substitution { name: "unsee", text: "♨_♨" },
    Substitution { name: "yuno", text: "ლ(ಠ益ಠლ)" },

    // Keyboard Shortcuts
    Substitution { name: "cmd-", text: "⌘-" },
    Substitution { name: "cmd", text: "⌘" },
    Substitution { name: "command", text: "⌘" },
    Substitution { name: "cntl", text: "⌃" },
    Substitution { name: "optn", text: "⌥" },
    Substitution { name: "option", text: "⌥" },
    Substitution { name: "shft", text: "⇧" },
    Substitution { name: "shift", text: "⇧" },

    // Smileys & People
    Substitution { name: "grin", text: "😀" },
    Substitution { name: "smiley", text: "😃" },
    Substitution { name: "smile", text: "😄" },
    Substitution { name: "grinning", text: "😁" },
    Substitution { name: "laughing", text: "😆" },
    Substitution { name: "sweat_smile", text: "😅" },
    Substitution { name: "rofl", text: "🤣" },
    Substitution { name: "joy", text: "😂" },
    Substitution { name: "slightsmile", text: "🙂" },
    Substitution { name: "upsidedown", text: "🙃" },
    Substitution { name: "meltingface", text: "🫠" },
    Substitution { name: "wink", text: "😉" },
    Substitution { name: "blush", text: "😊" },
    Substitution { name: "innocent", text: "😇" },
    Substitution { name: "hearteyessmile", text: "🥰" },
    Substitution { name: "hearteyes", text: "😍" },
    Substitution { name: "starstruck", text: "🤩" },
    Substitution { name: "kissing", text: "😗" },
    Substitution { name: "kissingheart", text: "😘" },
    Substitution { name: "relaxed", text: "☺️" },
    Substitution { name: "kissingclosedeyes", text: "😚" },
    Substitution { name: "kissingsmile", text: "😙" },
    Substitution { name: "yum", text: "😋" },
    Substitution { name: "tongueout", text: "😛" },
    Substitution { name: "tonguewink", text: "😜" },
    Substitution { name: "zany", text: "🤪" },
    Substitution { name: "tongueclosedeyes", text: "😝" },
    Substitution { name: "moneymouth", text: "🤑" },
    Substitution { name: "hugs", text: "🤗" },
    Substitution { name: "handovermouth", text: "🤭" },
    Substitution { name: "shush", text: "🫢" },
    Substitution { name: "thinking", text: "🤔" },
    Substitution { name: "salute", text: "🫡" },
    Substitution { name: "zipper", text: "🤐" },
    Substitution { name: "raisedeyebrow", text: "🤨" },
    Substitution { name: "neutral", text: "😐" },
    Substitution { name: "expressionless", text: "😑" },
    Substitution { name: "nomouth", text: "😶" },
    Substitution { name: "dottedline", text: "🫥" },
    Substitution { name: "cloudface", text: "😶‍🌫️" },
    Substitution { name: "smirk", text: "😏" },
    Substitution { name: "unamused", text: "😒" },
    Substitution { name: "eyeroll", text: "🙄" },
    Substitution { name: "grimace", text: "😬" },
    Substitution { name: "cringe", text: "😬" },
    Substitution { name: "lyingface", text: "🤥" },
    Substitution { name: "shakingface", text: "🫨" },
    Substitution { name: "relieved", text: "😌" },
    Substitution { name: "pensive", text: "😔" },
    Substitution { name: "sleepy", text: "😪" },
    Substitution { name: "drool", text: "🤤" },
    Substitution { name: "sleeping", text: "😴" },
    Substitution { name: "mask", text: "😷" },
    Substitution { name: "sick", text: "🤒" },
    Substitution { name: "bandage", text: "🤕" },
    Substitution { name: "nauseated", text: "🤢" },
    Substitution { name: "vomit", text: "🤮" },
    Substitution { name: "sneeze", text: "🤧" },
    Substitution { name: "hot", text: "🥵" },
    Substitution { name: "cold", text: "🥶" },
    Substitution { name: "woozy", text: "🥴" },
    Substitution { name: "dizzy", text: "😵" },
    Substitution { name: "spiraleyes", text: "😵‍💫" },
    Substitution { name: "explodinghead", text: "🤯" },
    Substitution { name: "cowboy", text: "🤠" },
    Substitution { name: "party", text: "🥳" },
    Substitution { name: "disguised", text: "🥸" },
    Substitution { name: "sunglasses", text: "😎" },
    Substitution { name: "nerd", text: "🤓" },
    Substitution { name: "monocle", text: "🧐" },
    Substitution { name: "confused", text: "😕" },
    Substitution { name: "faceexhaling", text: "😮‍💨" },
    Substitution { name: "worried", text: "😟" },
    Substitution { name: "slightfrown", text: "🙁" },
    Substitution { name: "frown", text: "☹️" },
    Substitution { name: "openmouth", text: "😮" },
    Substitution { name: "hushed", text: "😯" },
    Substitution { name: "astonished", text: "😲" },
    Substitution { name: "flushed", text: "😳" },
    Substitution { name: "pleading", text: "🥺" },
    Substitution { name: "holdingbacktears", text: "🥹" },
    Substitution { name: "frowning", text: "😦" },
    Substitution { name: "anguished", text: "😧" },
    Substitution { name: "fearful", text: "😨" },
    Substitution { name: "anxious", text: "😰" },
    Substitution { name: "sad", text: "😥" },
    Substitution { name: "cry", text: "😢" },
    Substitution { name: "sob", text: "😭" },
    Substitution { name: "scream", text: "😱" },
    Substitution { name: "omg", text: "😱" },
    Substitution { name: "confounded", text: "😖" },
    Substitution { name: "persevere", text: "😣" },
    Substitution { name: "disappointed", text: "😞" },
    Substitution { name: "sweat", text: "😓" },
    Substitution { name: "weary", text: "😩" },
    Substitution { name: "tired", text: "😫" },
    Substitution { name: "yawning", text: "🥱" },
    Substitution { name: "triumph", text: "😤" },
    Substitution { name: "pout", text: "😡" },
    Substitution { name: "angry", text: "😠" },
    Substitution { name: "cursing", text: "🤬" },
    Substitution { name: "smiling_imp", text: "😈" },
    Substitution { name: "imp", text: "👿" },
    Substitution { name: "skull", text: "💀" },
    Substitution { name: "crossbones", text: "☠️" },
    Substitution { name: "clown", text: "🤡" },
    Substitution { name: "poop", text: "💩" },
    Substitution { name: "ghost", text: "👻" },
    Substitution { name: "alien", text: "👽" },
    Substitution { name: "alienmonster", text: "👾" },
    Substitution { name: "robot", text: "🤖" },
    Substitution { name: "smilingcat", text: "😺" },
    Substitution { name: "grincat", text: "😸" },
    Substitution { name: "joycat", text: "😹" },
    Substitution { name: "heartcat", text: "😻" },
    Substitution { name: "smirkcat", text: "😼" },
    Substitution { name: "kissingcat", text: "😽" },
    Substitution { name: "screamcat", text: "🙀" },
    Substitution { name: "omgcat", text: "🙀" },
    Substitution { name: "cryingcat", text: "😿" },
    Substitution { name: "poutcat", text: "😾" },
    Substitution { name: "heart", text: "❤️" },
    Substitution { name: "orange_heart", text: "🧡" },
    Substitution { name: "yellow_heart", text: "💛" },
    Substitution { name: "green_heart", text: "💚" },
    Substitution { name: "blue_heart", text: "💙" },
    Substitution { name: "purple_heart", text: "💜" },
    Substitution { name: "brown_heart", text: "🤎" },
    Substitution { name: "black_heart", text: "🖤" },
    Substitution { name: "grey_heart", text: "🩶" },
    Substitution { name: "white_heart", text: "🤍" },
    Substitution { name: "pinkheart", text: "🩷" },
    Substitution { name: "lightheart", text: "🩵" },
    Substitution { name: "broken_heart", text: "💔" },
    Substitution { name: "heartexclamation", text: "❣️" },
    Substitution { name: "twohearts", text: "💕" },
    Substitution { name: "revolvingheart", text: "💞" },
    Substitution { name: "heartbeat", text: "💓" },
    Substitution { name: "growingheart", text: "💗" },
    Substitution { name: "sparklingheart", text: "💖" },
    Substitution { name: "heartarrow", text: "💘" },
    Substitution { name: "loveeyes", text: "😍" },
    Substitution { name: "kiss", text: "💋" },
    Substitution { name: "envelope", text: "💌" },
    Substitution { name: "cupid", text: "💘" },
    Substitution { name: "bouquet", text: "💐" },
    Substitution { name: "fire", text: "🔥" },
    Substitution { name: "heartfire", text: "❤️‍🔥" },
    Substitution { name: "mendingeart", text: "❤️‍🩹" },
    Substitution { name: "sparkles", text: "✨" },
    Substitution { name: "star", text: "⭐" },
    Substitution { name: "dizzystar", text: "💫" },
    Substitution { name: "sweat_drops", text: "💦" },
    Substitution { name: "dash", text: "💨" },
    Substitution { name: "boom", text: "💥" },
    Substitution { name: "wave", text: "👋" },
    Substitution { name: "raisedback", text: "🤚" },
    Substitution { name: "splayed", text: "🖐️" },
    Substitution { name: "hand", text: "✋" },
    Substitution { name: "vulcan", text: "🖖" },
    Substitution { name: "rightwardshand", text: "🫱" },
    Substitution { name: "leftwardshand", text: "🫲" },
    Substitution { name: "palmdown", text: "🫳" },
    Substitution { name: "palmup", text: "🫴" },
    Substitution { name: "leftwardspush", text: "🫷" },
    Substitution { name: "rightwardspush", text: "🫸" },
    Substitution { name: "okhand", text: "👌" },
    Substitution { name: "pinched", text: "🤌" },
    Substitution { name: "pinching", text: "🤏" },
    Substitution { name: "v", text: "✌️" },
    Substitution { name: "crossed", text: "🤞" },
    Substitution { name: "indexpoint", text: "🫰" },
    Substitution { name: "iloveyou", text: "🤟" },
    Substitution { name: "metal", text: "🤘" },
    Substitution { name: "callme", text: "🤙" },
    Substitution { name: "pointleft", text: "👈" },
    Substitution { name: "pointright", text: "👉" },
    Substitution { name: "pointup", text: "👆" },
    Substitution { name: "middlefinger", text: "🖕" },
    Substitution { name: "pointdown", text: "👇" },
    Substitution { name: "pointup2", text: "☝️" },
    Substitution { name: "indexleft", text: "🫵" },
    Substitution { name: "thumbsup", text: "👍" },
    Substitution { name: "thumbsdown", text: "👎" },
    Substitution { name: "fist", text: "✊" },
    Substitution { name: "facepunch", text: "👊" },
    Substitution { name: "leftfist", text: "🤛" },
    Substitution { name: "rightfist", text: "🤜" },
    Substitution { name: "clap", text: "👏" },
    Substitution { name: "raisehands", text: "🙌" },
    Substitution { name: "hearthand", text: "🫶" },
    Substitution { name: "openhands", text: "👐" },
    Substitution { name: "palmsup", text: "🤲" },
    Substitution { name: "handshake", text: "🤝" },
    Substitution { name: "pray", text: "🙏" },
    Substitution { name: "writing", text: "✍️" },
    Substitution { name: "nails", text: "💅" },
    Substitution { name: "selfie", text: "🤳" },
    Substitution { name: "muscle", text: "💪" },
    Substitution { name: "mechanicalarm", text: "🦾" },
    Substitution { name: "mechanicalleg", text: "🦿" },
    Substitution { name: "leg", text: "🦵" },
    Substitution { name: "foot", text: "🦶" },
    Substitution { name: "ear", text: "👂" },
    Substitution { name: "earwithhearing", text: "🦻" },
    Substitution { name: "nose", text: "👃" },
    Substitution { name: "brain", text: "🧠" },
    Substitution { name: "anatomicalheart", text: "🫀" },
    Substitution { name: "lungs", text: "🫁" },
    Substitution { name: "tooth", text: "🦷" },
    Substitution { name: "bone", text: "🦴" },
    Substitution { name: "eyes", text: "👀" },
    Substitution { name: "eye", text: "👁️" },
    Substitution { name: "tongue", text: "👅" },
    Substitution { name: "lips", text: "👄" },
    Substitution { name: "bitinglip", text: "🫦" },

    // Combined/Custom Emotes
    Substitution { name: "bullshit", text: "🐄💩" },
    Substitution { name: "catshit", text: "🐱💩" },
    Substitution { name: "dogshit", text: "🐶💩" },
    Substitution { name: "pandashit", text: "🐼💩" },
    Substitution { name: "horseshit", text: "🐴💩" },
    Substitution { name: "koalashit", text: "🐨💩" },
    Substitution { name: "batshit", text: "🦇💩" },
    Substitution { name: "shboatload", text: "💩🚢" },
    Substitution { name: "noevil", text: "🙈🙉🙊" },
];

pub fn process(substitution_name: &str) -> Option<&'static str> {
    let name = substitution_name.to_lowercase();
    SUBSTITUTIONS
        .iter()
        .find(|s| s.name == name)
        .map(|s| s.text)
}

pub fn list_substitutions() -> String {
    let mut output = vec!["Available text substitutions:".to_string()];
    for sub in SUBSTITUTIONS {
        let display_text = if sub.text.len() > 50 {
            format!("{}...", &sub.text[..50])
        } else {
            sub.text.to_string()
        };
        output.push(format!(
            "  {:15} - {}",
            sub.name, display_text
        ));
    }
    output.join("\n")
}

pub fn substitution_exists(name: &str) -> bool {
    let name = name.to_lowercase();
    SUBSTITUTIONS.iter().any(|s| s.name == name)
}

pub fn substitution_names() -> Vec<&'static str> {
    SUBSTITUTIONS.iter().map(|s| s.name).collect()
}
